---
name: Build Workflow
run-name: Build Workflow
on:
  pull_request:
  workflow_call:
    inputs:
      upload-artifacts:
        required: true
        type: boolean
      version:
        required: true
        type: string


jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version_major: steps.get-version.outputs.version_major
      version_minor: steps.get-version.outputs.version_minor
      version_patch: steps.get-version.outputs.version_patch
      is_valid: steps.get_version.outputs.is_valid
    steps:
      - name: Create version file
        id: get_version
        env:
          VERSION: ${{ case(inputs.version, inputs.version, 'v1.0.0') }}
        run: |
          echo VERSION ${VERSION}
          if ! grep -q -Eo 'v[0-9]+\.[0-9]+\.[0-9]+'; then
            echo "is_valid=false" >> "$GITHUB_OUTPUT"
          else
            echo "is_valid=true" >> "$GITHUB_OUTPUT"
          fi
          echo ${VERSION} | awk -F'[v.]' '{print "version_major=" $2}' >> "$GITHUB_OUTPUT"
          echo ${VERSION} | awk -F'[v.]' '{print "version_minor=" $3}' >> "$GITHUB_OUTPUT"
          echo ${VERSION} | awk -F'[v.]' '{print "version_patch=" $4}' >> "$GITHUB_OUTPUT"


  test:
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: DEBUG
        env:
          VERSION_MAJOR: needs.version.outputs.version_major
          VERSION_MINOR: needs.version.outputs.version_minor
          VERSION_PATCH: needs.version.outputs.version_patch
          IS_VALID: needs.version.outputs.is_valid
        run: |
          echo VERSION_MAJOR $VERSION_MAJOR
          echo VERSION_MINOR $VERSION_MINOR
          echo VERSION_PATCH $VERSION_PATCH
          echo IS_VALID $IS_VALID

  # build-linux:
  #   if: needs.version.outputs.is_valid == 'true'
  #   runs-on: ubuntu-latest
  #   needs: version
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v6
  
  #     - name: Set PATH
  #       run: |
  #         echo "/usr/local/cmake/bin:/usr/local/zig:\$PATH" > $GITHUB_PATH
      
  #     - name: Install CMake
  #       run: |
  #         curl -sS -L -o /tmp/cmake.tgz https://github.com/Kitware/CMake/releases/download/v4.3.3/cmake-4.3.3-linux-x86_64.tar.gz
  #         tar -zxvf /tmp/cmake.tgz -C /tmp
  #         sudo mkdir -p /usr/local/cmake
  #         sudo mv /tmp/cmake-4.3.3-linux-x86_64/* /usr/local/cmake/
  
  #     - name: Install Ninja
  #       run: |
  #         curl -sS -L -o /tmp/ninja.zip https://github.com/ninja-build/ninja/releases/download/v1.13.2/ninja-linux.zip
  #         sudo unzip -d /usr/bin /tmp/ninja.zip
  
  #     - name: Install Zig
  #       run: |
  #         curl -sS -L -o /tmp/zig.tar.xz https://ziglang.org/builds/zig-x86_64-linux-0.17.0-dev.813+2153f8143.tar.xz
  #         sudo mkdir -p /usr/local/zig
  #         tar -xvf /tmp/zig.tar.xz -C /tmp
  #         sudo mv /tmp/zig-x86_64-linux-0.17.0-dev.813+2153f8143/* /usr/local/zig
      
  #     - name: Build release
  #       run: |
  #         cmake --preset static-release -B out
  #         cmake --build out

  #     - name: Upload Linux artifact
  #       if: inputs.upload-artifacts
  #       uses: actions/upload-artifact@v7
  #       with:
  #         name: Linux artifact
  #         path: out/suffer2gether


  # build-windows:
  #   if: needs.version.outputs.is_valid == 'true'
  #   runs-on: windows-2025-vs2026
  #   needs: version
  #   defaults:
  #     run:
  #       shell: cmd
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v6

  #     - name: Build release
  #       env:
  #         VERSION_MAJOR: ${{ needs.version.outputs.version_major }}
  #         VERSION_MINOR: ${{ needs.version.outputs.version_minor }}
  #         VERSION_PATCH: ${{ needs.version.outputs.version_patch }}
  #       run: |
  #         call "C:\Program Files\Microsoft Visual Studio\18\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
  #         echo VERSION_MAJOR %VERSION_MAJOR%
  #         echo VERSION_MINOR %VERSION_MINOR%
  #         echo VERSION_PATCH %VERSION_PATCH%
  #         cmake --preset windows-x86-release -B out
  #         cmake --build out

  #     - name: Upload Windows MFC artifact
  #       if: inputs.upload-artifacts
  #       uses: actions/upload-artifact@v7
  #       with:
  #         name: Windows MFC artifact
  #         path: out/suffer2gether.exe

  #     - name: Upload Windows CLI artifact
  #       if: inputs.upload-artifacts
  #       uses: actions/upload-artifact@v7
  #       with:
  #         name: Windows CLI artifact
  #         path: out/suffer2gether-cli.exe
