---
name: Build Linux
run-name: ${{ github.actor }} test
on:
  - pull_request
jobs:
#  build-linux:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check out repository code
#        uses: actions/checkout@v6
#
#      - name: Set PATH
#        run: |
#          echo "/usr/local/cmake/bin:/usr/local/zig:\$PATH" > $GITHUB_PATH
#      
#      - name: Install CMake
#        run: |
#          curl -sS -L -o /tmp/cmake.tgz https://github.com/Kitware/CMake/releases/download/v4.3.3/cmake-4.3.3-linux-x86_64.tar.gz
#          tar -zxvf /tmp/cmake.tgz -C /tmp
#          sudo mkdir -p /usr/local/cmake
#          sudo mv /tmp/cmake-4.3.3-linux-x86_64/* /usr/local/cmake/
#
#      - name: Install Ninja
#        run: |
#          curl -sS -L -o /tmp/ninja.zip https://github.com/ninja-build/ninja/releases/download/v1.13.2/ninja-linux.zip
#          sudo unzip -d /usr/bin /tmp/ninja.zip
#
#      - name: Install Zig
#        run: |
#          curl -sS -L -o /tmp/zig.tar.xz https://ziglang.org/builds/zig-x86_64-linux-0.17.0-dev.813+2153f8143.tar.xz
#          sudo mkdir -p /usr/local/zig
#          tar -xvf /tmp/zig.tar.xz -C /tmp
#          sudo mv /tmp/zig-x86_64-linux-0.17.0-dev.813+2153f8143/* /usr/local/zig
#      
#      - name: Build release
#        run: |
#          cmake --preset static-release -B out
#          cmake --build out

  build-windows:
    runs-on: windows-2025-vs2026
    defaults:
      run:
        shell: cmd
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Set PATH
        run: |
          echo "%RUNNER_TEMP%\cmake\bin" >> $GITHUB_PATH
          echo "%RUNNER_TEMP%\ninja" >> $GITHUB_PATH
          # echo "C:\Program Files\Microsoft Visual Studio\18\Enterprise\VC\Tools\MSVC\14.51.36231\bin\Hostx86\x86" >> $GITHUB_PATH

      - name: Install CMake
        shell: powershell
        run: |
          invoke-webrequest -uri https://github.com/Kitware/CMake/releases/download/v4.3.3/cmake-4.3.3-windows-x86_64.zip -outfile "$env:RUNNER_TEMP\cmake.zip"
          7z x "$env:RUNNER_TEMP\cmake.zip" -o"$env:RUNNER_TEMP\cmake"

      - name: Install Ninja
        shell: powershell
        run: |
          Invoke-WebRequest -Uri  https://github.com/ninja-build/ninja/releases/download/v1.13.2/ninja-win.zip -OutFile "$env:RUNNER_TEMP\ninja.zip"
          7z x "$env:RUNNER_TEMP\ninja.zip" -o"$env:RUNNER_TEMP\ninja"

      - name: Debug
        run: |
          call "C:\Program Files\Microsoft Visual Studio\18\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
          cmake --version
          ninja --version
          cl --version
      # - name: Build release
      #   run: |
      #     cmake --preset windows-x86-release -B out
      #     cmake --build out
